spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ms-management-idtech
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  liquibase:
    change-log: classpath:/liquibase/changelog-master.yml

rabbitmq:
  queue:
    student: student-card-queue
    mail: student-mail-queue

client:
  payments:
    url: http://localhost:8082




server:
  port: 9898